# Generated by Django 4.1 on 2022-09-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_add_field_course_in_group_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ManyToManyField(to='account.photo'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ManyToManyField(to='account.photo'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('photo',)},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='student',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='teacher',
        ),
    ]
