# Generated by Django 4.0.6 on 2022-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_student_photo_teacher_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='account.photo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='account.photo'),
        ),
    ]
