# Generated by Django 4.0.6 on 2022-08-22 18:36

import account.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('learning', '0005_create_answer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.test')),
            ],
            options={
                'verbose_name': 'test_attempt',
                'verbose_name_plural': 'test_attempts',
            },
            bases=(models.Model, account.mixins.DateTimeMixinModel),
        ),
    ]
