# Generated by Django 4.0.6 on 2022-08-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_create_attempt_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
    ]
