# Generated by Django 4.0.6 on 2022-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_delete_score_field_test_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
